hotregion1: "output/NDD/NDD_hotregions.txt"
hotregion2: "output/COAD/COAD_hotregions.txt"
tumor1: "NDD"
tumor2: "COAD"
distance: 10
compare_dir: "output/NDDvsCOAD/"
structures_dir: "/lab/projects1/GRUMP/CLUMP-master/January_17_2023/"